#!/bin/sh

# initialize X resource database (if file ~/.Xresources is present on the system)
xrdb -load ~/.Xresources

# Mapping caps lock to escape
xmodmap -e 'clear Lock' #ensures you're not stuck in CAPS on mode
xmodmap -e 'keycode 0x42=Escape' #remaps the keyboard so CAPS LOCK=ESC
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
done
unset f

# Starting xcompmgr
xcompmgr &

#xrandr --output DisplayPort-1 --mode 1920x1200 --rotate right
xrandr --output DisplayPort-1 --mode 1920x1200

feh --bg-scale /home/james/Pictures/mountains.jpg

exec xmonad
#exec i3
#exec startlxde

